import type {
  Cliente,
  Producto,
  DocumentoElectronico,
  ResolucionDian,
  ConfiguracionEmpresa,
  Usuario,
  DashboardSummary,
  EstadoDian,
  ItemFactura,
  Proveedor,
  InventarioItem,
  MovimientoInventario,
  Caja,
  SesionCaja,
  MovimientoCaja,
  ProductoFacturacion,
} from './types';

// ============================================================================
// Empresa
// ============================================================================

export const mockEmpresa: ConfiguracionEmpresa = {
  id: 'emp-1',
  nit: '901.548.326',
  dv: '7',
  razonSocial: 'Innova Andina S.A.S.',
  nombreComercial: 'Innova Andina',
  regimenTributario: 'responsable_iva',
  responsabilidadesFiscales: ['O-03', 'O-07', 'O-15'],
  codigoCIIU: '6201',
  direccion: 'Cra. 13 # 82-12, Of. 401',
  ciudad: 'Bogotá',
  departamento: 'Cundinamarca',
  codigoPostal: '110221',
  telefono: '+57 601 742 8800',
  email: 'facturacion@innovaandina.co',
  logoUrl: '',
  ambiente: 'habilitacion',
  certificadoDigitalCargado: true,
  fechaVencimientoCertificado: '2026-09-04',
  monedaLocal: 'COP',
  cuentaContableVentas: '4135',
  retenedor: true,
  granContribuyente: false,
};

// ============================================================================
// Clientes
// ============================================================================

export const mockClientes: Cliente[] = [
  {
    id: 'cli-1',
    tipoIdentificacion: 'NIT',
    identificacion: '830.045.791',
    dv: '2',
    razonSocial: 'Comercializadora Andina Ltda.',
    nombreComercial: 'Andina Distribución',
    email: 'compras@andina.com.co',
    telefono: '+57 310 555 0142',
    direccion: 'Av. Caracas # 54-30',
    ciudad: 'Bogotá',
    departamento: 'Cundinamarca',
    regimenTributario: 'responsable_iva',
    responsabilidadesFiscales: ['O-03'],
    codigoCIIU: '4711',
    codigoPostal: '110111',
    persona: 'juridica',
    createdAt: '2025-11-12T10:00:00Z',
  },
  {
    id: 'cli-2',
    tipoIdentificacion: 'CC',
    identificacion: '52.884.331',
    razonSocial: 'Carlos Andrés Restrepo',
    email: 'restrepo.ca@gmail.com',
    telefono: '+57 314 220 9087',
    direccion: 'Calle 12 # 7-41, Apto 302',
    ciudad: 'Medellín',
    departamento: 'Antioquia',
    regimenTributario: 'no_responsable',
    responsabilidadesFiscales: ['O-01'],
    persona: 'natural',
    createdAt: '2026-01-04T08:30:00Z',
  },
  {
    id: 'cli-3',
    tipoIdentificacion: 'NIT',
    identificacion: '900.221.004',
    dv: '5',
    razonSocial: 'Tecnología Pacífico S.A.',
    email: 'facturacion@tecnicopacifico.co',
    telefono: '+57 602 889 1100',
    direccion: 'Calle 5N # 28-11',
    ciudad: 'Cali',
    departamento: 'Valle del Cauca',
    regimenTributario: 'responsable_iva',
    responsabilidadesFiscales: ['O-03', 'O-07'],
    codigoCIIU: '4651',
    persona: 'juridica',
    createdAt: '2025-09-22T14:00:00Z',
  },
  {
    id: 'cli-4',
    tipoIdentificacion: 'NIT',
    identificacion: '1.134.209',
    dv: '1',
    razonSocial: 'Constructora Caribe S.A.S.',
    email: 'contabilidad@conscaribe.co',
    telefono: '+57 5 366 4400',
    direccion: 'Av. San Martín # 42-18',
    ciudad: 'Barranquilla',
    departamento: 'Atlántico',
    regimenTributario: 'regimen_simple',
    responsabilidadesFiscales: ['O-47'],
    codigoCIIU: '4120',
    persona: 'juridica',
    regimenSimple: true,
    createdAt: '2026-02-18T09:15:00Z',
  },
  {
    id: 'cli-5',
    tipoIdentificacion: 'CE',
    identificacion: 'A-220.119',
    razonSocial: 'María Fernanda Londoño',
    email: 'mf.londono@outlook.com',
    telefono: '+57 318 740 5520',
    direccion: 'Cra. 70 # 10-22',
    ciudad: 'Pereira',
    departamento: 'Risaralda',
    regimenTributario: 'no_responsable',
    responsabilidadesFiscales: ['O-01'],
    persona: 'natural',
    createdAt: '2026-03-01T11:45:00Z',
  },
];

// ============================================================================
// Productos
// ============================================================================

export const mockProductos: Producto[] = [
  {
    id: 'prod-1',
    codigo: 'SUS-PRO-001',
    codigoUNSPSC: '81101700',
    nombre: 'Suscripción Plataforma Pro (mensual)',
    descripcion: 'Plan mensual módulo de facturación, 1.000 documentos/mes.',
    tipoItem: 'servicio',
    precioUnitario: 189000,
    unidadMedida: 'SER',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    activo: true,
  },
  {
    id: 'prod-2',
    codigo: 'SRV-IMP-002',
    codigoUNSPSC: '81101600',
    nombre: 'Implementación onboarding',
    descripcion: 'Servicio de implementación y capacitación inicial.',
    tipoItem: 'servicio',
    precioUnitario: 1200000,
    unidadMedida: 'SER',
    iva: 19,
    inc: 0,
    aplicaReteFuente: true,
    aplicaReteICA: true,
    aplicaReteIVA: false,
    tasaReteFuente: 0.025,
    tasaReteICA: 0.0069,
    activo: true,
  },
  {
    id: 'prod-3',
    codigo: 'LIC-USU-010',
    codigoUNSPSC: '81111700',
    nombre: 'Licencia usuario adicional',
    descripcion: 'Usuario adicional en plataforma (mensual).',
    tipoItem: 'servicio',
    precioUnitario: 32000,
    unidadMedida: 'SER',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    activo: true,
  },
  {
    id: 'prod-4',
    codigo: 'SRV-CAP-005',
    codigoUNSPSC: '86121600',
    nombre: 'Capacitación funcional (4h)',
    descripcion: 'Sesión de capacitación funcional remota.',
    tipoItem: 'servicio',
    precioUnitario: 280000,
    unidadMedida: 'HUR',
    iva: 19,
    inc: 0,
    aplicaReteFuente: true,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    tasaReteFuente: 0.04,
    activo: true,
  },
  {
    id: 'prod-5',
    codigo: 'SRV-SOP-008',
    codigoUNSPSC: '81111500',
    nombre: 'Soporte prioritario (paquete 10h)',
    descripcion: 'Banco de horas de soporte prioritario.',
    tipoItem: 'servicio',
    precioUnitario: 640000,
    unidadMedida: 'HUR',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: true,
    aplicaReteIVA: false,
    tasaReteICA: 0.0069,
    activo: true,
  },
  {
    id: 'prod-6',
    codigo: 'SRV-AUD-012',
    codigoUNSPSC: '82111500',
    nombre: 'Auditoría DIAN anual',
    descripcion: 'Revisión y auditoría de cumplimiento DIAN.',
    tipoItem: 'servicio',
    precioUnitario: 1450000,
    unidadMedida: 'SER',
    iva: 19,
    inc: 0,
    aplicaReteFuente: true,
    aplicaReteICA: true,
    aplicaReteIVA: false,
    tasaReteFuente: 0.06,
    tasaReteICA: 0.01104,
    activo: true,
  },
  {
    id: 'prod-7',
    codigo: 'HW-LAP-020',
    codigoUNSPSC: '43211507',
    nombre: 'Laptop Pro 14" i7 16GB',
    descripcion: 'Laptop empresarial, 16GB RAM, SSD 512GB.',
    tipoItem: 'bien',
    precioUnitario: 4_350_000,
    unidadMedida: 'UND',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    stock: 24,
    stockMinimo: 5,
    costoUnitario: 3_680_000,
    cuentaContable: '1435',
    activo: true,
  },
  {
    id: 'prod-8',
    codigo: 'HW-MON-021',
    codigoUNSPSC: '43211909',
    nombre: 'Monitor 27" 4K UHD',
    descripcion: 'Monitor LED 27" resolución 3840x2160.',
    tipoItem: 'bien',
    precioUnitario: 1_290_000,
    unidadMedida: 'UND',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    stock: 3,
    stockMinimo: 8,
    costoUnitario: 1_080_000,
    cuentaContable: '1435',
    activo: true,
  },
  {
    id: 'prod-9',
    codigo: 'HW-TEC-022',
    codigoUNSPSC: '43211706',
    nombre: 'Teclado mecánico inalámbrico',
    descripcion: 'Teclado mecánico retroiluminado, layout español.',
    tipoItem: 'bien',
    precioUnitario: 189_000,
    unidadMedida: 'UND',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    stock: 42,
    stockMinimo: 10,
    costoUnitario: 142_000,
    cuentaContable: '1435',
    activo: true,
  },
  {
    id: 'prod-10',
    codigo: 'CN-PAP-030',
    codigoUNSPSC: '14111507',
    nombre: 'Resma papel A4 75g (500 hojas)',
    descripcion: 'Resma de papel bond blanco, tamaño A4.',
    tipoItem: 'bien',
    precioUnitario: 18_500,
    unidadMedida: 'Paquete',
    iva: 19,
    inc: 0,
    aplicaReteFuente: false,
    aplicaReteICA: false,
    aplicaReteIVA: false,
    stock: 156,
    stockMinimo: 30,
    costoUnitario: 13_800,
    cuentaContable: '1435',
    activo: true,
  },
];

// ============================================================================
// Resoluciones DIAN
// ============================================================================

export const mockResoluciones: ResolucionDian[] = [
  {
    id: 'res-1',
    numeroResolucion: '1876400000000456',
    tipoDocumento: 'factura_venta',
    prefijo: 'FE',
    rangoDesde: 1,
    rangoHasta: 25000,
    consecutivoActual: 18423,
    fechaVigenciaDesde: '2025-01-01',
    fechaVigenciaHasta: '2027-01-01',
    activa: true,
    claveTecnica: 'clave-tecnica-hab-2025',
  },
  {
    id: 'res-2',
    numeroResolucion: '1876400000000891',
    tipoDocumento: 'nota_credito',
    prefijo: 'NC',
    rangoDesde: 1,
    rangoHasta: 5000,
    consecutivoActual: 312,
    fechaVigenciaDesde: '2025-01-01',
    fechaVigenciaHasta: '2027-01-01',
    activa: true,
  },
  {
    id: 'res-3',
    numeroResolucion: '1876400000000934',
    tipoDocumento: 'documento_soporte',
    prefijo: 'DS',
    rangoDesde: 1,
    rangoHasta: 3000,
    consecutivoActual: 2104,
    fechaVigenciaDesde: '2025-06-01',
    fechaVigenciaHasta: '2026-08-01',
    activa: true,
  },
];

// ============================================================================
// Documentos electrónicos
// ============================================================================

function buildItems(
  productos: { productoId: string; descripcion: string; cantidad: number; precio: number; iva: number; descuento?: number }[]
): ItemFactura[] {
  return productos.map((p) => {
    const gross = p.cantidad * p.precio;
    const net = gross - (p.descuento || 0);
    return {
      productoId: p.productoId,
      descripcion: p.descripcion,
      cantidad: p.cantidad,
      precioUnitario: p.precio,
      descuento: p.descuento,
      iva: p.iva,
      subtotal: net,
    };
  });
}

function docTotals(items: ItemFactura[]) {
  const subtotal = items.reduce((s, i) => s + i.subtotal, 0);
  const totalIva = items.reduce((s, i) => s + (i.subtotal * i.iva) / 100, 0);
  const total = subtotal + totalIva;
  return { subtotal, totalIva, totalInc: 0, totalRetenciones: 0, totalDescuentos: 0, totalCargos: 0, total };
}

export const mockDocumentos: DocumentoElectronico[] = [
  {
    id: 'doc-001',
    tipoDocumento: 'factura_venta',
    tipoOperacion: '01',
    numero: 'FE-018423',
    resolucionId: 'res-1',
    clienteId: 'cli-1',
    cliente: mockClientes[0],
    items: buildItems([
      { productoId: 'prod-1', descripcion: 'Suscripción Plataforma Pro (mensual)', cantidad: 1, precio: 189000, iva: 19 },
      { productoId: 'prod-3', descripcion: 'Licencia usuario adicional x3', cantidad: 3, precio: 32000, iva: 19 },
    ]),
    formaPago: 'credito',
    medioPago: 'transferencia',
    ambiente: 'habilitacion',
    estadoDian: 'aceptado',
    cufe: 'abc73d8e1f9a04c219b7e3d6f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
    qrCode: 'https://catalogo-vpfe-hab.dian.gov.co/document/qr?abc73d8e1f9a',
    fechaEmision: '2026-07-14T14:22:00Z',
    fechaVencimiento: '2026-08-13T14:22:00Z',
    moneda: 'COP',
    createdAt: '2026-07-14T14:22:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-1', descripcion: 'Suscripción Plataforma Pro (mensual)', cantidad: 1, precio: 189000, iva: 19 },
      { productoId: 'prod-3', descripcion: 'Licencia usuario adicional x3', cantidad: 3, precio: 32000, iva: 19 },
    ])),
  },
  {
    id: 'doc-002',
    tipoDocumento: 'factura_venta',
    tipoOperacion: '01',
    numero: 'FE-018422',
    resolucionId: 'res-1',
    clienteId: 'cli-3',
    cliente: mockClientes[2],
    items: buildItems([
      { productoId: 'prod-2', descripcion: 'Implementación onboarding', cantidad: 1, precio: 1200000, iva: 19 },
      { productoId: 'prod-4', descripcion: 'Capacitación funcional (4h)', cantidad: 2, precio: 280000, iva: 19 },
    ]),
    formaPago: 'contado',
    medioPago: 'transferencia',
    ambiente: 'habilitacion',
    estadoDian: 'pendiente_envio',
    fechaEmision: '2026-07-15T10:05:00Z',
    moneda: 'COP',
    createdAt: '2026-07-15T10:05:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-2', descripcion: 'Implementación onboarding', cantidad: 1, precio: 1200000, iva: 19 },
      { productoId: 'prod-4', descripcion: 'Capacitación funcional (4h)', cantidad: 2, precio: 280000, iva: 19 },
    ])),
  },
  {
    id: 'doc-003',
    tipoDocumento: 'factura_venta',
    tipoOperacion: '01',
    numero: 'FE-018421',
    resolucionId: 'res-1',
    clienteId: 'cli-4',
    cliente: mockClientes[3],
    items: buildItems([
      { productoId: 'prod-5', descripcion: 'Soporte prioritario (paquete 10h)', cantidad: 1, precio: 640000, iva: 19 },
    ]),
    formaPago: 'contado',
    medioPago: 'tarjeta_credito',
    ambiente: 'habilitacion',
    estadoDian: 'rechazado',
    motivoRechazo: 'Código 502: El archivo XML no cumple con la estructura esperada. Falta elemento cbc:TaxAmount en la línea de impuesto.',
    fechaEmision: '2026-07-12T16:40:00Z',
    moneda: 'COP',
    createdAt: '2026-07-12T16:40:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-5', descripcion: 'Soporte prioritario (paquete 10h)', cantidad: 1, precio: 640000, iva: 19 },
    ])),
  },
  {
    id: 'doc-004',
    tipoDocumento: 'factura_venta',
    tipoOperacion: '01',
    numero: 'FE-018420',
    resolucionId: 'res-1',
    clienteId: 'cli-2',
    cliente: mockClientes[1],
    items: buildItems([
      { productoId: 'prod-1', descripcion: 'Suscripción Plataforma Pro (mensual)', cantidad: 1, precio: 189000, iva: 19 },
    ]),
    formaPago: 'contado',
    medioPago: 'nequi',
    ambiente: 'habilitacion',
    estadoDian: 'enviado',
    fechaEmision: '2026-07-11T08:15:00Z',
    moneda: 'COP',
    createdAt: '2026-07-11T08:15:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-1', descripcion: 'Suscripción Plataforma Pro (mensual)', cantidad: 1, precio: 189000, iva: 19 },
    ])),
  },
  {
    id: 'doc-005',
    tipoDocumento: 'nota_credito',
    tipoOperacion: '08',
    numero: 'NC-000312',
    resolucionId: 'res-2',
    clienteId: 'cli-1',
    cliente: mockClientes[0],
    items: buildItems([
      { productoId: 'prod-3', descripcion: 'Ajuste licencia usuario adicional', cantidad: 1, precio: 32000, iva: 19 },
    ]),
    formaPago: 'credito',
    medioPago: 'transferencia',
    ambiente: 'habilitacion',
    estadoDian: 'aceptado',
    cude: 'cude7a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
    fechaEmision: '2026-07-09T11:00:00Z',
    moneda: 'COP',
    documentoReferencia: {
      tipoDocumento: 'factura_venta',
      numero: 'FE-018410',
      cufe: 'abc73d8e1f9a04c219b7e3d6f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
      razonReferencia: 'Anulación parcial',
    },
    createdAt: '2026-07-09T11:00:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-3', descripcion: 'Ajuste licencia usuario adicional', cantidad: 1, precio: 32000, iva: 19 },
    ])),
  },
  {
    id: 'doc-006',
    tipoDocumento: 'factura_venta',
    tipoOperacion: '01',
    numero: 'FE-018419',
    resolucionId: 'res-1',
    clienteId: 'cli-5',
    cliente: mockClientes[4],
    items: buildItems([
      { productoId: 'prod-4', descripcion: 'Capacitación funcional (4h)', cantidad: 1, precio: 280000, iva: 19 },
    ]),
    formaPago: 'contado',
    medioPago: 'daviplata',
    ambiente: 'habilitacion',
    estadoDian: 'anulado',
    fechaEmision: '2026-07-08T09:30:00Z',
    moneda: 'COP',
    createdAt: '2026-07-08T09:30:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-4', descripcion: 'Capacitación funcional (4h)', cantidad: 1, precio: 280000, iva: 19 },
    ])),
  },
  {
    id: 'doc-007',
    tipoDocumento: 'documento_soporte',
    tipoOperacion: '12',
    numero: 'DS-002104',
    resolucionId: 'res-3',
    clienteId: 'cli-2',
    cliente: mockClientes[1],
    items: buildItems([
      { productoId: 'prod-6', descripcion: 'Auditoría DIAN anual', cantidad: 1, precio: 1450000, iva: 19 },
    ]),
    formaPago: 'contado',
    medioPago: 'efectivo',
    ambiente: 'habilitacion',
    estadoDian: 'aceptado',
    cufe: 'cufe8b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9',
    fechaEmision: '2026-07-05T13:10:00Z',
    moneda: 'COP',
    createdAt: '2026-07-05T13:10:00Z',
    ...docTotals(buildItems([
      { productoId: 'prod-6', descripcion: 'Auditoría DIAN anual', cantidad: 1, precio: 1450000, iva: 19 },
    ])),
  },
];

// ============================================================================
// Usuarios
// ============================================================================

export const mockUsuarios: Usuario[] = [
  {
    id: 'usr-1',
    nombre: 'Diana Marcela Gómez',
    email: 'diana.gomez@innovaandina.co',
    rol: 'admin',
    pin: '1234',
    estado: 'activo',
    ultimoAcceso: '2026-07-16T13:10:00Z',
  },
  {
    id: 'usr-2',
    nombre: 'Sebastián Ospina',
    email: 'sebastian.ospina@innovaandina.co',
    rol: 'supervisor',
    pin: '2468',
    estado: 'activo',
    ultimoAcceso: '2026-07-15T18:40:00Z',
  },
  {
    id: 'usr-3',
    nombre: 'Laura Vélez',
    email: 'laura.velez@innovaandina.co',
    rol: 'contador',
    pin: '1357',
    estado: 'activo',
    ultimoAcceso: '2026-07-14T09:00:00Z',
  },
  {
    id: 'usr-4',
    nombre: 'Andrés Felipe Quintero',
    email: 'andres.quintero@innovaandina.co',
    rol: 'cajero',
    pin: '9999',
    estado: 'activo',
    ultimoAcceso: '2026-07-16T12:00:00Z',
  },
  {
    id: 'usr-5',
    nombre: 'Valentina Ruiz',
    email: 'valentina.ruiz@innovaandina.co',
    rol: 'solo_lectura',
    estado: 'pendiente',
    ultimoAcceso: undefined,
  },
];

// ============================================================================
// Dashboard
// ============================================================================

export const mockDashboard: DashboardSummary = {
  facturasMes: 184,
  pendientesEnvio: 7,
  rechazadas: 3,
  ingresosTotales: 48_920_000,
  ventasPorMes: [
    { mes: 'Feb', total: 28_400_000 },
    { mes: 'Mar', total: 31_900_000 },
    { mes: 'Abr', total: 35_600_000 },
    { mes: 'May', total: 33_200_000 },
    { mes: 'Jun', total: 41_800_000 },
    { mes: 'Jul', total: 48_920_000 },
  ],
  distribucionEstados: [
    { estado: 'aceptado', cantidad: 142 },
    { estado: 'enviado', cantidad: 18 },
    { estado: 'pendiente_envio', cantidad: 7 },
    { estado: 'rechazado', cantidad: 3 },
    { estado: 'anulado', cantidad: 5 },
    { estado: 'borrador', cantidad: 9 },
  ],
  ultimosDocumentos: mockDocumentos.slice(0, 5),
  certificadoPorVencer: false,
  resolucionPorAgotar: true,
};

// ============================================================================
// Proveedores
// ============================================================================

export const mockProveedores: Proveedor[] = [
  {
    id: 'prov-1',
    tipoIdentificacion: 'NIT',
    identificacion: '830.002.564',
    dv: '1',
    razonSocial: 'Distribuidora Tecnológica S.A.',
    nombreComercial: 'Distec',
    email: 'ventas@distec.co',
    telefono: '+57 601 745 9900',
    direccion: 'Calle 80 # 45-20',
    ciudad: 'Bogotá',
    departamento: 'Cundinamarca',
    regimenTributario: 'responsable_iva',
    responsabilidadesFiscales: ['O-03', 'O-08'],
    codigoCIIU: '4651',
    persona: 'juridica',
    banco: 'Bancolombia',
    tipoCuenta: 'corriente',
    numeroCuenta: '0123-4567-89',
    formaPagoPreferida: 'credito',
    plazoPagoDias: 30,
    activo: true,
    createdAt: '2025-08-15T10:00:00Z',
  },
  {
    id: 'prov-2',
    tipoIdentificacion: 'NIT',
    identificacion: '900.118.220',
    dv: '3',
    razonSocial: 'Papel y Oficina Andina Ltda.',
    nombreComercial: 'PapelAndina',
    email: 'pedidos@papelandina.co',
    telefono: '+57 604 256 7788',
    direccion: 'Cra. 50 # 10-15',
    ciudad: 'Medellín',
    departamento: 'Antioquia',
    regimenTributario: 'responsable_iva',
    responsabilidadesFiscales: ['O-03'],
    codigoCIIU: '4721',
    persona: 'juridica',
    banco: 'Banco de Bogotá',
    tipoCuenta: 'ahorros',
    numeroCuenta: '9876-5432-10',
    formaPagoPreferida: 'contado',
    plazoPagoDias: 0,
    activo: true,
    createdAt: '2025-10-03T08:00:00Z',
  },
  {
    id: 'prov-3',
    tipoIdentificacion: 'CC',
    identificacion: '43.901.220',
    razonSocial: 'Julián Restrepo (freelance)',
    email: 'julian.r@gmail.com',
    telefono: '+57 311 555 0190',
    direccion: 'Calle 7 # 32-11',
    ciudad: 'Manizales',
    departamento: 'Caldas',
    regimenTributario: 'no_responsable',
    responsabilidadesFiscales: ['O-01'],
    persona: 'natural',
    banco: 'Nequi',
    formaPagoPreferida: 'contado',
    plazoPagoDias: 0,
    activo: true,
    createdAt: '2026-02-20T14:30:00Z',
  },
  {
    id: 'prov-4',
    tipoIdentificacion: 'NIT',
    identificacion: '860.512.330',
    dv: '0',
    razonSocial: 'Servicios Cloud Colombia S.A.S.',
    nombreComercial: 'CloudCol',
    email: 'facturacion@cloudcol.co',
    telefono: '+57 602 884 1100',
    direccion: 'Av. 6N # 28-40',
    ciudad: 'Cali',
    departamento: 'Valle del Cauca',
    regimenTributario: 'responsable_iva',
    responsabilidadesFiscales: ['O-03', 'O-07'],
    codigoCIIU: '6311',
    persona: 'juridica',
    banco: 'Davivienda',
    tipoCuenta: 'corriente',
    numeroCuenta: '4567-8901-23',
    formaPagoPreferida: 'credito',
    plazoPagoDias: 45,
    activo: true,
    createdAt: '2025-06-12T09:00:00Z',
  },
];

// ============================================================================
// Inventario
// ============================================================================

export const mockInventario: InventarioItem[] = [
  {
    id: 'inv-1',
    productoId: 'prod-7',
    producto: mockProductos[6],
    stockActual: 24,
    stockMinimo: 5,
    stockMaximo: 60,
    ubicacion: 'Bodega A - Estante 3',
    costoUnitario: 3_680_000,
    valorizado: 24 * 3_680_000,
    ultimoMovimiento: '2026-07-10T11:00:00Z',
  },
  {
    id: 'inv-2',
    productoId: 'prod-8',
    producto: mockProductos[7],
    stockActual: 3,
    stockMinimo: 8,
    stockMaximo: 40,
    ubicacion: 'Bodega A - Estante 5',
    costoUnitario: 1_080_000,
    valorizado: 3 * 1_080_000,
    ultimoMovimiento: '2026-07-13T15:30:00Z',
  },
  {
    id: 'inv-3',
    productoId: 'prod-9',
    producto: mockProductos[8],
    stockActual: 42,
    stockMinimo: 10,
    stockMaximo: 80,
    ubicacion: 'Bodega B - Estante 1',
    costoUnitario: 142_000,
    valorizado: 42 * 142_000,
    ultimoMovimiento: '2026-07-09T09:15:00Z',
  },
  {
    id: 'inv-4',
    productoId: 'prod-10',
    producto: mockProductos[9],
    stockActual: 156,
    stockMinimo: 30,
    stockMaximo: 300,
    ubicacion: 'Bodega B - Estante 7',
    costoUnitario: 13_800,
    valorizado: 156 * 13_800,
    ultimoMovimiento: '2026-07-14T10:00:00Z',
  },
];

export const mockMovimientosInventario: MovimientoInventario[] = [
  {
    id: 'mov-inv-1',
    productoId: 'prod-7',
    producto: mockProductos[6],
    tipo: 'entrada',
    cantidad: 20,
    stockResultante: 24,
    motivo: 'Compra a Distribuidora Tecnológica S.A.',
    referencia: 'OC-2026-0142',
    proveedorId: 'prov-1',
    usuario: 'Sebastián Ospina',
    fecha: '2026-07-10T11:00:00Z',
  },
  {
    id: 'mov-inv-2',
    productoId: 'prod-8',
    producto: mockProductos[7],
    tipo: 'salida',
    cantidad: 5,
    stockResultante: 3,
    motivo: 'Venta FE-018418',
    referencia: 'FE-018418',
    documentoElectronicoId: 'doc-004',
    usuario: 'Sebastián Ospina',
    fecha: '2026-07-13T15:30:00Z',
  },
  {
    id: 'mov-inv-3',
    productoId: 'prod-9',
    producto: mockProductos[8],
    tipo: 'entrada',
    cantidad: 40,
    stockResultante: 42,
    motivo: 'Compra a Papel y Oficina Andina',
    referencia: 'OC-2026-0150',
    proveedorId: 'prov-2',
    usuario: 'Laura Vélez',
    fecha: '2026-07-09T09:15:00Z',
  },
  {
    id: 'mov-inv-4',
    productoId: 'prod-10',
    producto: mockProductos[9],
    tipo: 'ajuste',
    cantidad: -4,
    stockResultante: 156,
    motivo: 'Ajuste por conteo físico de inventario',
    referencia: 'AJUSTE-2026-007',
    usuario: 'Laura Vélez',
    fecha: '2026-07-14T10:00:00Z',
  },
  {
    id: 'mov-inv-5',
    productoId: 'prod-7',
    producto: mockProductos[6],
    tipo: 'devolucion',
    cantidad: 1,
    stockResultante: 24,
    motivo: 'Devolución por defecto de fábrica',
    referencia: 'DEV-2026-003',
    usuario: 'Sebastián Ospina',
    fecha: '2026-07-11T08:00:00Z',
  },
];

// ============================================================================
// Cajas
// ============================================================================

export const mockCajas: Caja[] = [
  { id: 'caja-1', nombre: 'Caja Principal', sucursal: 'Bogotá HQ', responsableActual: 'Sebastián Ospina', activa: true, saldoBase: 200000 },
  { id: 'caja-2', nombre: 'Caja Sucursal Norte', sucursal: 'Medellín', responsableActual: undefined, activa: true, saldoBase: 100000 },
  { id: 'caja-3', nombre: 'Caja Online', sucursal: 'Virtual', responsableActual: 'Diana Marcela Gómez', activa: true, saldoBase: 0 },
];

export const mockSesionesCaja: SesionCaja[] = [
  {
    id: 'ses-1',
    cajaId: 'caja-1',
    caja: mockCajas[0],
    usuarioId: 'usr-2',
    usuario: 'Sebastián Ospina',
    fechaApertura: '2026-07-16T08:00:00Z',
    saldoInicial: 200000,
    ingresos: 0,
    egresos: 50000,
    ventas: 1_890_000,
    saldoFinal: 200000 + 1_890_000 - 50000,
    estado: 'abierta',
    movimientos: [
      {
        id: 'mc-1',
        sesionId: 'ses-1',
        tipo: 'venta',
        monto: 1_890_000,
        concepto: 'Venta FE-018423 — Suscripción Pro',
        medioPago: 'transferencia',
        documentoElectronicoId: 'doc-001',
        usuario: 'Sebastián Ospina',
        fecha: '2026-07-16T14:22:00Z',
      },
      {
        id: 'mc-2',
        sesionId: 'ses-1',
        tipo: 'egreso',
        monto: 50000,
        concepto: 'Gasto de envío courier',
        medioPago: 'efectivo',
        usuario: 'Sebastián Ospina',
        fecha: '2026-07-16T11:30:00Z',
      },
    ],
  },
  {
    id: 'ses-2',
    cajaId: 'caja-1',
    caja: mockCajas[0],
    usuarioId: 'usr-2',
    usuario: 'Sebastián Ospina',
    fechaApertura: '2026-07-15T08:00:00Z',
    fechaCierre: '2026-07-15T18:00:00Z',
    saldoInicial: 200000,
    ingresos: 0,
    egresos: 30000,
    ventas: 2_340_000,
    saldoFinal: 200000 + 2_340_000 - 30000,
    estado: 'cerrada',
    movimientos: [],
  },
  {
    id: 'ses-3',
    cajaId: 'caja-3',
    caja: mockCajas[2],
    usuarioId: 'usr-1',
    usuario: 'Diana Marcela Gómez',
    fechaApertura: '2026-07-14T09:00:00Z',
    fechaCierre: '2026-07-14T20:00:00Z',
    saldoInicial: 0,
    ingresos: 0,
    egresos: 0,
    ventas: 6_120_000,
    saldoFinal: 6_120_000,
    estado: 'cerrada',
    movimientos: [],
  },
];

export const mockMovimientosCaja: MovimientoCaja[] = mockSesionesCaja.flatMap((s) => s.movimientos);

// ============================================================================
// Productos de facturación (configuración DIAN avanzada)
// ============================================================================

export const mockProductosFacturacion: ProductoFacturacion[] = [
  {
    id: 'pf-1',
    productoId: 'prod-1',
    producto: mockProductos[0],
    categoria: 'servicios',
    precioConImpuestos: 189000 * 1.19,
    tributos: [
      { tipo: 'iva', porcentaje: 19, baseImponible: 189000, valor: 189000 * 0.19, codigoDIAN: '01' },
    ],
    codigoEstandar: '001',
    codigoUNSPSC: '81101700',
    unidadMedidaDIAN: 'SER',
    cuentaContableVentas: '4135',
    cuentaContableCompras: '6135',
    requiereExportacion: false,
    excluidoDeIva: false,
    bienDeCapital: false,
    activo: true,
  },
  {
    id: 'pf-2',
    productoId: 'prod-2',
    producto: mockProductos[1],
    categoria: 'servicios',
    precioConImpuestos: 1200000 * 1.19,
    tributos: [
      { tipo: 'iva', porcentaje: 19, baseImponible: 1200000, valor: 1200000 * 0.19, codigoDIAN: '01' },
      { tipo: 'retefuente', porcentaje: 2.5, baseImponible: 1200000, valor: 1200000 * 0.025, codigoDIAN: '06', esRetencion: true },
      { tipo: 'reteica', porcentaje: 0.69, baseImponible: 1200000, valor: 1200000 * 0.0069, codigoDIAN: '07', esRetencion: true },
    ],
    codigoEstandar: '002',
    codigoUNSPSC: '81101600',
    unidadMedidaDIAN: 'SER',
    cuentaContableVentas: '4135',
    cuentaContableCompras: '6135',
    requiereExportacion: false,
    excluidoDeIva: false,
    bienDeCapital: false,
    activo: true,
  },
  {
    id: 'pf-3',
    productoId: 'prod-7',
    producto: mockProductos[6],
    categoria: 'tecnologia',
    precioConImpuestos: 4_350_000 * 1.19,
    tributos: [
      { tipo: 'iva', porcentaje: 19, baseImponible: 4_350_000, valor: 4_350_000 * 0.19, codigoDIAN: '01' },
    ],
    codigoEstandar: '020',
    codigoUNSPSC: '43211507',
    unidadMedidaDIAN: 'UND',
    cuentaContableVentas: '4135',
    cuentaContableCompras: '6205',
    requiereExportacion: false,
    excluidoDeIva: false,
    bienDeCapital: true,
    activo: true,
  },
  {
    id: 'pf-4',
    productoId: 'prod-10',
    producto: mockProductos[9],
    categoria: 'papeleria',
    precioConImpuestos: 18_500 * 1.19,
    tributos: [
      { tipo: 'iva', porcentaje: 19, baseImponible: 18_500, valor: 18_500 * 0.19, codigoDIAN: '01' },
    ],
    codigoEstandar: '030',
    codigoUNSPSC: '14111507',
    unidadMedidaDIAN: 'Paquete',
    cuentaContableVentas: '4135',
    cuentaContableCompras: '6115',
    requiereExportacion: false,
    excluidoDeIva: false,
    bienDeCapital: false,
    activo: true,
  },
];
